// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prefer DIRECT_URL for the CLI (migrate, generate). It points at the
    // Supabase Session Pooler / direct connection which supports prepared
    // statements. Fall back to DATABASE_URL if DIRECT_URL is unset.
    // At app runtime we still read DATABASE_URL directly in lib/db.ts.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
